Controllers/FilesListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MUAT.Models;

namespace MUAT.Controllers
{
    [Authorize]
    public class FilesListsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: FilesLists
        public ActionResult Index()
        {
            return View(db.FilesLists.ToList());
        }

        // GET: FilesLists/ShowSearchForm
        public ActionResult ShowSearchForm()
        {
            return View();
        }

        // GET: FilesLists/ShowSearchResults
        public ActionResult ShowSearchResults(String SearchPhrase)
        {
            return View("Index", db.FilesLists.Where(j=> j.FileName.Contains(SearchPhrase)).ToList());
        }

        // GET: FilesLists/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FilesList filesList = db.FilesLists.Find(id);
            if (filesList == null)
            {
                return HttpNotFound();
            }
            return View(filesList);
        }

        // GET: FilesLists/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: FilesLists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FileName,FileDate,FileDetails")] FilesList filesList)
        {
            if (ModelState.IsValid)
            {
                db.FilesLists.Add(filesList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(filesList);
        }

        // GET: FilesLists/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FilesList filesList = db.FilesLists.Find(id);
            if (filesList == null)
            {
                return HttpNotFound();
            }
            return View(filesList);
        }

        // POST: FilesLists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FileName,FileDate,FileDetails")] FilesList filesList)
        {
            if (ModelState.IsValid)
            {
                db.Entry(filesList).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(filesList);
        }

        // GET: FilesLists/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FilesList filesList = db.FilesLists.Find(id);
            if (filesList == null)
            {
                return HttpNotFound();
            }
            return View(filesList);
        }

        // POST: FilesLists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FilesList filesList = db.FilesLists.Find(id);
            db.FilesLists.Remove(filesList);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/GenererDocsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MUAT.Models;

namespace MUAT.Controllers
{
    [Authorize]
    public class GenererDocsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GenererDocs
        public ActionResult Index()
        {
            return View(db.GenererDocs.ToList());
        }

        // GET: GenererDocs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GenererDoc genererDoc = db.GenererDocs.Find(id);
            if (genererDoc == null)
            {
                return HttpNotFound();
            }
            return View(genererDoc);
        }

        // GET: GenererDocs/Create
        public ActionResult Create()
        {
            return View();
        }
        
        // GET: GenererDocs/CreateCPS
        public ActionResult CreateCPS()
        {
            return View();
        }
        
        // GET: GenererDocs/CreateRC
        public ActionResult CreateRC()
        {
            return View();
        }

        // GET: GenererDocs/CreateAvisFr
        public ActionResult CreateAvisFr()
        {
            return View();
        }
        
        // GET: GenererDocs/CreateAvisAr
        public ActionResult CreateAvisAr()
        {
            return View();
        }

        // POST: GenererDocs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Document")] GenererDoc genererDoc)
        {
            if (ModelState.IsValid)
            {
                db.GenererDocs.Add(genererDoc);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(genererDoc);
        }

        // GET: GenererDocs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GenererDoc genererDoc = db.GenererDocs.Find(id);
            if (genererDoc == null)
            {
                return HttpNotFound();
            }
            return View(genererDoc);
        }

        // POST: GenererDocs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Document")] GenererDoc genererDoc)
        {
            if (ModelState.IsValid)
            {
                db.Entry(genererDoc).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(genererDoc);
        }

        // GET: GenererDocs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GenererDoc genererDoc = db.GenererDocs.Find(id);
            if (genererDoc == null)
            {
                return HttpNotFound();
            }
            return View(genererDoc);
        }

        // POST: GenererDocs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GenererDoc genererDoc = db.GenererDocs.Find(id);
            db.GenererDocs.Remove(genererDoc);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/ListeMarchesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MUAT.Models;

namespace MUAT.Controllers
{
    [Authorize]
    public class ListeMarchesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ListeMarches
        public ActionResult Index()
        {
            return View(db.ListeMarches.ToList());
        }

        // GET: ListeMarches/ShowSearchFormD
        public ActionResult ShowSearchFormD()
        {
            return View();
        }

        // GET: ListeMarches/ShowSearchResultsD
        public ActionResult ShowSearchResultsD(String SearchWord)
        {
            return View("Index", db.ListeMarches.Where(j => j.TitreMarche.Contains(SearchWord)).ToList());
        }

        // GET: ListeMarches/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListeMarches listeMarches = db.ListeMarches.Find(id);
            if (listeMarches == null)
            {
                return HttpNotFound();
            }
            return View(listeMarches);
        }

        // GET: ListeMarches/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ListeMarches/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,TitreMarche,LienMarche,ListeDocs,Status")] ListeMarches listeMarches)
        {
            if (ModelState.IsValid)
            {
                db.ListeMarches.Add(listeMarches);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(listeMarches);
        }

        // GET: ListeMarches/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListeMarches listeMarches = db.ListeMarches.Find(id);
            if (listeMarches == null)
            {
                return HttpNotFound();
            }
            return View(listeMarches);
        }

        // POST: ListeMarches/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,TitreMarche,LienMarche,ListeDocs,Status")] ListeMarches listeMarches)
        {
            if (ModelState.IsValid)
            {
                db.Entry(listeMarches).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(listeMarches);
        }

        // GET: ListeMarches/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListeMarches listeMarches = db.ListeMarches.Find(id);
            if (listeMarches == null)
            {
                return HttpNotFound();
            }
            return View(listeMarches);
        }

        // POST: ListeMarches/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ListeMarches listeMarches = db.ListeMarches.Find(id);
            db.ListeMarches.Remove(listeMarches);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="~/favicon.ico" type="image/x-icon" />
</head>
<body style="display:flex">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MUAT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Marchés", "", "ListeMarches")</li>
                    <li>@Html.ActionLink("Rechercher Marché", "ShowSearchFormD", "ListeMarches")</li>
                    <li>@Html.ActionLink("Documents", "", "FilesLists")</li>
                    <li>@Html.ActionLink("Rechercher Document", "ShowSearchForm", "FilesLists")</li>
                    <li>@Html.ActionLink("Générer Documents", "", "GenererDocs")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer style="margin-top:auto">
            <div style="align-items:center; display:flex; justify-content:center">
                <img src="https://muat.gov.ma/sites/all/themes/multipurpose/logo.png" style="width:10%;height:10%;" />
                <p>&copy; @DateTime.Now.Year - Ministère de l'Aménagement du Territoire National, de l'Urbanisme, de l'Habitat et de la Politique de la Ville .</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutGenDoc.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MUAT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Marchés", "", "ListeMarches")</li>
                    <li>@Html.ActionLink("Rechercher Marché", "ShowSearchFormD", "ListeMarches")</li>
                    <li>@Html.ActionLink("Documents", "", "FilesLists")</li>
                    <li>@Html.ActionLink("Rechercher Document", "ShowSearchForm", "FilesLists")</li>
                    <li>@Html.ActionLink("Générer Documents", "", "GenererDocs")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div style="align-items:center; display:flex; justify-content:center">
                <img src="https://muat.gov.ma/sites/all/themes/multipurpose/logo.png" style="width:10%;height:10%;" />
                <p>&copy; @DateTime.Now.Year - Ministère de l'Aménagement du Territoire National, de l'Urbanisme, de l'Habitat et de la Politique de la Ville .</p>
            </div>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>